// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xktdzfcwydiatzgbrozr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrdGR6ZmN3eWRpYXR6Z2Jyb3pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMjIyMTQsImV4cCI6MjA3Mjg5ODIxNH0.BmR78k3Pgs21tZtFfMMNdk8JgZxxwwjM5LgzOQGNrdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});